packages:
  - packages/*

ignoredBuiltDependencies:
  - esbuild

catalogs:
  build:
    vite: ^6.3.4
    typescript: ^5.8.3
  format:
    '@ianvs/prettier-plugin-sort-imports': ^4.4.1
    prettier-plugin-packagejson: ^2.5.10
    prettier: ^3.5.3
  lint:
    '@eslint/js': ^9.26.0
    '@eslint/eslintrc': ^3.3.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react: ^7.37.5
    eslint: ^9.26.0
    typescript-eslint: ^8.31.1
    jiti: ^2.4.2
  test:
    vitest: ^3.1.2
    '@vitest/browser': ^3.1.2
    '@playwright/test': ^1.52.0
  types:
    '@types/node': ^22.15.3
  script:
    'taze': '^19.0.4'
